package org.votingsystem.model;

/**
* @author jgzornoza
* Licencia: https://github.com/jgzornoza/SistemaVotacion/wiki/Licencia
*/
public enum TypeVS {

    ACCESS_REQUEST,

    ITEM_REQUEST,
    ITEMS_REQUEST,

    VOTING_EVENT,
    VOTEVS,
    VOTEVS_CANCELLED,
    CANCEL_VOTE,

    CONTROL_CENTER_ASSOCIATION,
    MANIFEST_EVENT,
    CLAIM_EVENT,

    EVENT_CANCELLATION,
    BACKUP_REQUEST,
    SEND_SMIME_VOTE,
    MANIFEST_SIGN,
    SMIME_CLAIM_SIGNATURE,
    CLAIM_PUBLISHING,
    MANIFEST_PUBLISHING,
    VOTING_PUBLISHING,

    ANONYMOUS_REPRESENTATIVE_SELECTION,
    REPRESENTATIVE;
}
