package org.controlacceso.clientegwt.client;

public enum HistoryToken {
	
	CREAR_MANIFIESTO, VOTACIONES, CREAR_RECLAMACION, CREAR_VOTACION,
	FIRMAR_MANIFIESTO, FIRMAR_RECLAMACION, VOTAR, MANIFIESTOS, HERRAMIENTA_VALIDACION,
	RECLAMACIONES, DOCUMENTACION, BUSQUEDAS, OBTENIDA_INFO_SERVIDOR, TEST, 
	REPRESENTATIVES_PAGE, NEW_REPRESENTATIVE, EDIT_REPRESENTATIVE, REPRESENTATIVE_CONFIG, 
	REPRESENTATIVE_DETAILS, DUMMY_TOKEN;

}
