package org.votingsystem.model;

public enum OperationVSBase implements OperationVS {

    SOLICITUD_ACCESO,
    ANULADOR_VOTO,
    ASOCIAR_CENTRO_CONTROL, 
    CAMBIO_ESTADO_CENTRO_CONTROL_SMIME, 
    SOLICITUD_COPIA_SEGURIDAD, 
    PUBLICACION_MANIFIESTO_PDF, 
    FIRMA_MANIFIESTO_PDF, 
    PUBLICACION_RECLAMACION_SMIME,
    FIRMA_RECLAMACION_SMIME, 
    PUBLICACION_VOTACION_SMIME, 
    ENVIO_VOTO_SMIME,
    MENSAJE_APPLET, 
    ANULAR_VOTO,
    ANULAR_SOLICITUD_ACCESO,
    CANCELAR_EVENTO,
    GUARDAR_RECIBO_VOTO,
    MENSAJE_CIERRE_APPLET,
    NEW_REPRESENTATIVE,
    REPRESENTATIVE_VOTING_HISTORY_REQUEST,
    REPRESENTATIVE_SELECTION,
    REPRESENTATIVE_ACCREDITATIONS_REQUEST,
    MENSAJE_HERRAMIENTA_VALIDACION,
    REPRESENTATIVE_REVOKE;
}
