package org.sistemavotacion.test.panel;

import java.awt.Color;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import org.sistemavotacion.modelo.OpcionEvento;

/**
* @author jgzornoza
* Licencia: https://github.com/jgzornoza/SistemaVotacion/blob/master/licencia.txt
*/
public class OpcionVotacionPanel extends javax.swing.JPanel {
    
    OpcionEvento opcion;
    private Border normalTextBorder;
    private String mensajeError;

    public OpcionVotacionPanel(OpcionEvento opcion) {
        initComponents();
        this.opcion = opcion;
        normalTextBorder = numeroVotosTextField.getBorder();
        opcionLabel.setText("<html><b>" + opcion.getContenido() + "</b></html>");
        if(opcion.getNumeroVotos() != null)
            numeroVotosTextField.setText(opcion.getNumeroVotos().toString());
    }

    public OpcionEvento getOpcion() {
        if(!"".equals(numeroVotosTextField.getText().trim())) {
            try {
                opcion.setNumeroVotos(new Integer(numeroVotosTextField.getText().trim()));
            } catch(Exception ex) {
                mensajeError = "<html>El valor debe ser numérico</html>";
                return null;
            }
        } else {
            mensajeError = "<html>El campo no puede ir vacío</html>";
            return null;
        }
        mensajeError = null;
        return opcion;
    }
    
    public void setError(boolean isError) {
        if(isError) {
            numeroVotosTextField.setBorder(new LineBorder(Color.RED,2));
        } else {
            numeroVotosTextField.setBorder(normalTextBorder);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionLabel = new javax.swing.JLabel();
        numeroVotosTextField = new javax.swing.JTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/sistemavotacion/test/panel/Bundle"); // NOI18N
        numeroVotosTextField.setText(bundle.getString("OpcionVotacionPanel.numeroVotosTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(opcionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroVotosTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(numeroVotosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField numeroVotosTextField;
    private javax.swing.JLabel opcionLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the mensajeError
     */
    public String getMensajeError() {
        return mensajeError;
    }

    /**
     * @param mensajeError the mensajeError to set
     */
    public void setMensajeError(String mensajeError) {
        this.mensajeError = mensajeError;
    }
}
