package org.sistemavotacion.test.panel;

import java.awt.Container;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JDialog;
import net.miginfocom.swing.MigLayout;
import org.sistemavotacion.modelo.OpcionEvento;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
* @author jgzornoza
* Licencia: https://github.com/jgzornoza/SistemaVotacion/blob/master/licencia.txt
*/
public class OpcionesPanel extends javax.swing.JPanel implements ContenedorOpciones {
    
    private static Logger logger = LoggerFactory.getLogger(OpcionesPanel.class);

    /** Creates new form OpcionesPanel */
    public OpcionesPanel() {
        initComponents();
        setLayout(new MigLayout());
    }
    
    Set<String> opciones = new HashSet<String>();
    
    public void borrarOpcion (String opcion) {
    	opciones.remove(opcion);
    	dibujarOpciones();
    }
    
    public void anyadirOpcion (String opcionAnyadida) {
        opciones.add(opcionAnyadida);
        dibujarOpciones();
    }

    public void anyadirCampo (String campoAnyadido) {
        opciones.add(campoAnyadido);
        dibujarOpciones();
    }

    public List<OpcionEvento> obtenerOpciones () {
        List<OpcionEvento> opcionesDeEvento = new ArrayList<OpcionEvento>();
        for (String opcion : opciones) {
            OpcionEvento opcionDeEvento = new OpcionEvento();
            opcionDeEvento.setContenido(opcion);
            opcionesDeEvento.add(opcionDeEvento);
        }
        return opcionesDeEvento;
    }

    private void dibujarOpciones () {
        removeAll();
        repaint();
        for (String opcion:opciones) {
            OpcionPanel opcionPanel = new OpcionPanel();
            opcionPanel.setText(opcion);
            opcionPanel.setContenedor(this);
            add(opcionPanel, "wrap");
        }
        Container container = this.getTopLevelAncestor();
        if (container instanceof JDialog) {
            ((JDialog)this.getTopLevelAncestor()).pack();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
