package org.sistemavotacion.test.panel;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import javax.swing.*;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import org.sistemavotacion.modelo.ActorConIP;
import org.sistemavotacion.modelo.Evento;
import org.sistemavotacion.modelo.Respuesta;
import org.sistemavotacion.test.ContextoPruebas;
import org.sistemavotacion.test.MainFrame;
import org.sistemavotacion.test.dialogo.*;
import org.sistemavotacion.test.modelo.VotingSimulationData;
import org.sistemavotacion.test.simulation.SimulatorListener;
import org.sistemavotacion.test.simulation.VotingProcessSimulator;
import org.sistemavotacion.test.simulation.VotingSimulator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
* @author jgzornoza
* Licencia: https://github.com/jgzornoza/SistemaVotacion/wiki/Licencia
*/
public class VotacionesPanel extends JPanel implements 
        HyperlinkListener, SimulatorListener<VotingSimulationData> {
    
    private static Logger logger = LoggerFactory.getLogger(VotacionesPanel.class);
    
    public enum Estado {SIMULACION, RECOGIDA_DATOS}

    private Evento evento;
    private Estado estado = Estado.RECOGIDA_DATOS;
    private List<String> accessRequesterrorList;
    private List<String> votingerrorList;
    private VotingSimulator votacion;
    private HashMap<String, ActorConIP> hashMapActores = null;
    private Frame parentFrame = null;
    private MainFrame mainFrame = null;
    
    private ExecutorService executorPool = null;
    
    /**
     * Creates new form VotacionesPanel
     */
    public VotacionesPanel() {
        initComponents();
        urlCentroControlPanel.setVisible(false);
        publicacionConvocatoriaPanel.setVisible(false);
        datosSimulacionPanel.setVisible(false);
        asuntoConvocatoriaLabel.setVisible(false);
        lanzarSimulacionButton.setVisible(false);
        contadorPanel.setVisible(false);
        erroresSolicitudesButton.setVisible(false);
        erroresVotosButton.setVisible(false);
        anularVotosButton.setVisible(false);
    }
    
    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        this.parentFrame = MainFrame.getFrames()[0];
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        publicacionConvocatoriaPanel = new javax.swing.JPanel();
        mensajePublicacionLabel = new javax.swing.JLabel();
        publicarButton = new javax.swing.JButton();
        datosSimulacionPanel = new javax.swing.JPanel();
        infoEventoButton = new javax.swing.JButton();
        datosSimulacionButton = new javax.swing.JButton();
        asuntoConvocatoriaLabel = new javax.swing.JLabel();
        lanzarSimulacionButton = new javax.swing.JButton();
        erroresSolicitudesButton = new javax.swing.JButton();
        erroresVotosButton = new javax.swing.JButton();
        contadorPanel = new javax.swing.JPanel();
        contadorSolicitudesErrorLabel = new javax.swing.JLabel();
        contadorVotosLabel = new javax.swing.JLabel();
        contadorVotosValidadosLabel = new javax.swing.JLabel();
        contadorVotosErrorLabel = new javax.swing.JLabel();
        timePanel = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        digitalClockPanel = new org.sistemavotacion.test.panel.DigitalClockPanel();
        anularVotosButton = new javax.swing.JButton();
        centroControlPanel = new javax.swing.JPanel();
        urlCentroControlPanel = new javax.swing.JPanel();
        centroControlLabel = new javax.swing.JLabel();
        centrosDeControlComboBox = new javax.swing.JComboBox();
        infoServidorButton = new javax.swing.JButton();
        asociarCentroControlButton = new javax.swing.JButton();
        createUserBaseButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/sistemavotacion/test/panel/Bundle"); // NOI18N
        mensajePublicacionLabel.setText(bundle.getString("VotacionesPanel.mensajePublicacionLabel.text")); // NOI18N

        publicarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/publish.png"))); // NOI18N
        publicarButton.setText(bundle.getString("VotacionesPanel.publicarButton.text")); // NOI18N
        publicarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout publicacionConvocatoriaPanelLayout = new javax.swing.GroupLayout(publicacionConvocatoriaPanel);
        publicacionConvocatoriaPanel.setLayout(publicacionConvocatoriaPanelLayout);
        publicacionConvocatoriaPanelLayout.setHorizontalGroup(
            publicacionConvocatoriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicacionConvocatoriaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(publicacionConvocatoriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensajePublicacionLabel)
                    .addComponent(publicarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        publicacionConvocatoriaPanelLayout.setVerticalGroup(
            publicacionConvocatoriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicacionConvocatoriaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensajePublicacionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publicarButton))
        );

        infoEventoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information-white.png"))); // NOI18N
        infoEventoButton.setText(bundle.getString("VotacionesPanel.infoEventoButton.text")); // NOI18N
        infoEventoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoEventoButtonActionPerformed(evt);
            }
        });

        datosSimulacionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_16x16.png"))); // NOI18N
        datosSimulacionButton.setText(bundle.getString("VotacionesPanel.datosSimulacionButton.text")); // NOI18N
        datosSimulacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosSimulacionButtonActionPerformed(evt);
            }
        });

        asuntoConvocatoriaLabel.setText(bundle.getString("VotacionesPanel.asuntoConvocatoriaLabel.text")); // NOI18N

        lanzarSimulacionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gnome-run.png"))); // NOI18N
        lanzarSimulacionButton.setText(bundle.getString("VotacionesPanel.lanzarSimulacionButton.text")); // NOI18N
        lanzarSimulacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzarSimulacionButtonActionPerformed(evt);
            }
        });

        erroresSolicitudesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png"))); // NOI18N
        erroresSolicitudesButton.setText(bundle.getString("VotacionesPanel.erroresSolicitudesButton.text")); // NOI18N
        erroresSolicitudesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erroresSolicitudesButtonActionPerformed(evt);
            }
        });

        erroresVotosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png"))); // NOI18N
        erroresVotosButton.setText(bundle.getString("VotacionesPanel.erroresVotosButton.text")); // NOI18N
        erroresVotosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erroresVotosButtonActionPerformed(evt);
            }
        });

        contadorPanel.setBackground(java.awt.Color.white);
        contadorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        contadorSolicitudesErrorLabel.setText(bundle.getString("VotacionesPanel.contadorSolicitudesErrorLabel.text")); // NOI18N

        contadorVotosLabel.setText(bundle.getString("VotacionesPanel.contadorVotosLabel.text")); // NOI18N

        contadorVotosValidadosLabel.setText(bundle.getString("VotacionesPanel.contadorVotosValidadosLabel.text")); // NOI18N

        contadorVotosErrorLabel.setText(bundle.getString("VotacionesPanel.contadorVotosErrorLabel.text")); // NOI18N

        timePanel.setBackground(java.awt.Color.white);

        timeLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        timeLabel.setText(bundle.getString("VotacionesPanel.timeLabel.text")); // NOI18N

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timePanelLayout.createSequentialGroup()
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(digitalClockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel)
                    .addComponent(digitalClockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout contadorPanelLayout = new javax.swing.GroupLayout(contadorPanel);
        contadorPanel.setLayout(contadorPanelLayout);
        contadorPanelLayout.setHorizontalGroup(
            contadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contadorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contadorVotosValidadosLabel)
                    .addComponent(contadorVotosLabel)
                    .addComponent(contadorSolicitudesErrorLabel)
                    .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contadorVotosErrorLabel))
                .addContainerGap(729, Short.MAX_VALUE))
        );
        contadorPanelLayout.setVerticalGroup(
            contadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contadorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contadorVotosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contadorVotosValidadosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contadorSolicitudesErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contadorVotosErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        anularVotosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gtk-cancel.png"))); // NOI18N
        anularVotosButton.setText(bundle.getString("VotacionesPanel.anularVotosButton.text")); // NOI18N
        anularVotosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anularVotosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosSimulacionPanelLayout = new javax.swing.GroupLayout(datosSimulacionPanel);
        datosSimulacionPanel.setLayout(datosSimulacionPanelLayout);
        datosSimulacionPanelLayout.setHorizontalGroup(
            datosSimulacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosSimulacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosSimulacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contadorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(datosSimulacionPanelLayout.createSequentialGroup()
                        .addComponent(infoEventoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asuntoConvocatoriaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(datosSimulacionPanelLayout.createSequentialGroup()
                        .addGroup(datosSimulacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosSimulacionPanelLayout.createSequentialGroup()
                                .addComponent(erroresSolicitudesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(erroresVotosButton))
                            .addGroup(datosSimulacionPanelLayout.createSequentialGroup()
                                .addComponent(datosSimulacionButton)
                                .addGap(18, 18, 18)
                                .addComponent(lanzarSimulacionButton)
                                .addGap(18, 18, 18)
                                .addComponent(anularVotosButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        datosSimulacionPanelLayout.setVerticalGroup(
            datosSimulacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosSimulacionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(datosSimulacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoEventoButton)
                    .addComponent(asuntoConvocatoriaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosSimulacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datosSimulacionButton)
                    .addComponent(lanzarSimulacionButton)
                    .addComponent(anularVotosButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosSimulacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(erroresSolicitudesButton)
                    .addComponent(erroresVotosButton))
                .addContainerGap())
        );

        centroControlPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        centroControlLabel.setText(bundle.getString("VotacionesPanel.centroControlLabel.text")); // NOI18N
        centroControlLabel.setToolTipText(bundle.getString("VotacionesPanel.centroControlLabel.toolTipText")); // NOI18N

        centrosDeControlComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        centrosDeControlComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centrosDeControlComboBoxActionPerformed(evt);
            }
        });

        infoServidorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information-white.png"))); // NOI18N
        infoServidorButton.setText(bundle.getString("VotacionesPanel.infoServidorButton.text")); // NOI18N
        infoServidorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoServidorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout urlCentroControlPanelLayout = new javax.swing.GroupLayout(urlCentroControlPanel);
        urlCentroControlPanel.setLayout(urlCentroControlPanelLayout);
        urlCentroControlPanelLayout.setHorizontalGroup(
            urlCentroControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urlCentroControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(centroControlLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centrosDeControlComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoServidorButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        urlCentroControlPanelLayout.setVerticalGroup(
            urlCentroControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urlCentroControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(centrosDeControlComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(centroControlLabel)
                .addComponent(infoServidorButton))
        );

        asociarCentroControlButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pair_16x16.png"))); // NOI18N
        asociarCentroControlButton.setText(bundle.getString("VotacionesPanel.asociarCentroControlButton.text")); // NOI18N
        asociarCentroControlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asociarCentroControlButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centroControlPanelLayout = new javax.swing.GroupLayout(centroControlPanel);
        centroControlPanel.setLayout(centroControlPanelLayout);
        centroControlPanelLayout.setHorizontalGroup(
            centroControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centroControlPanelLayout.createSequentialGroup()
                .addComponent(urlCentroControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(asociarCentroControlButton)
                .addContainerGap())
        );
        centroControlPanelLayout.setVerticalGroup(
            centroControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centroControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(centroControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(urlCentroControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asociarCentroControlButton))
                .addContainerGap())
        );

        createUserBaseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group_16x16.png"))); // NOI18N
        createUserBaseButton.setText(bundle.getString("VotacionesPanel.createUserBaseButton.text")); // NOI18N
        createUserBaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datosSimulacionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centroControlPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(publicacionConvocatoriaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createUserBaseButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(centroControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createUserBaseButton)
                    .addComponent(publicacionConvocatoriaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosSimulacionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void infoServidorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoServidorButtonActionPerformed
        logger.debug("infoServidorButtonActionPerformed ");
        ActorConIP selectedControlCenter  = 
                hashMapActores.get(centrosDeControlComboBox.getSelectedItem());
        InfoServidorDialog infoServidorDialog = new InfoServidorDialog(
                parentFrame, false, selectedControlCenter);
                infoServidorDialog.setVisible(true);
    }//GEN-LAST:event_infoServidorButtonActionPerformed

    private void asociarCentroControlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asociarCentroControlButtonActionPerformed
        AsociarCentroControlDialog asociarCentroControlDialog = 
                new AsociarCentroControlDialog(parentFrame, false);
        asociarCentroControlDialog.setVisible(true);        
    }//GEN-LAST:event_asociarCentroControlButtonActionPerformed

    private void centrosDeControlComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centrosDeControlComboBoxActionPerformed
        ActorConIP centroControl = hashMapActores.get(
                centrosDeControlComboBox.getSelectedItem());
        ContextoPruebas.INSTANCE.setControlCenter(centroControl);
    }//GEN-LAST:event_centrosDeControlComboBoxActionPerformed

    private void publicarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicarButtonActionPerformed
        CrearVotacionDialog crearVotacionDialog = new CrearVotacionDialog(
                parentFrame, false);
        crearVotacionDialog.setVisible(true);
    }//GEN-LAST:event_publicarButtonActionPerformed

    private void infoEventoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoEventoButtonActionPerformed
        InfoEventoDialog infoEventoDialog = new InfoEventoDialog(
                parentFrame, false, evento);
        infoEventoDialog.setVisible(true);
    }//GEN-LAST:event_infoEventoButtonActionPerformed

    private void datosSimulacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosSimulacionButtonActionPerformed
        if(ContextoPruebas.INSTANCE.getUserBaseData() == null) {
            MensajeDialog errorDialog = new MensajeDialog(
                    parentFrame, true);
            errorDialog.setMessage(ContextoPruebas.INSTANCE.getString("userBaseDataNotFoundErrorMsg"), 
                ContextoPruebas.INSTANCE.getString("errorLbl"));
        } else {
            DatosSimulacionDialog datosSimulacionDialog = new DatosSimulacionDialog(
                    parentFrame, false, evento,
                    ContextoPruebas.INSTANCE.getUserBaseData());   
            datosSimulacionDialog.setVisible(true);
        }
    }//GEN-LAST:event_datosSimulacionButtonActionPerformed

    private void lanzarSimulacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzarSimulacionButtonActionPerformed
        switch(estado) {
            case RECOGIDA_DATOS:
                estado = Estado.SIMULACION;
                datosSimulacionButton.setEnabled(false);
                lanzarSimulacionButton.setIcon(new javax.swing.ImageIcon(
                        getClass().getResource("/images/loading.gif")));
                lanzarSimulacionButton.setText("Parar simulación");
                erroresSolicitudesButton.setVisible(false);
                erroresVotosButton.setVisible(false);
                actualizarContadorSolicitudesError(0);
                actualizarContadorVotosLanzados(0);
                actualizarContadorVotosValidados(0);
                actualizarContadorVotosError(0);
                try {
                    VotingSimulationData simulationData = new VotingSimulationData();
                    simulationData.setUserBaseData(ContextoPruebas.
                            INSTANCE.getUserBaseData());
                    simulationData.setAccessControlURL(ContextoPruebas.INSTANCE.
                            getAccessControl().getServerURL());
                    simulationData.setControlCenterURL(ContextoPruebas.
                            INSTANCE.getControlCenter().getServerURL());
                    simulationData.setEvento(ContextoPruebas.INSTANCE.getEvento());
                    VotingProcessSimulator simulation = new 
                        VotingProcessSimulator(simulationData, null);
                    ContextoPruebas.INSTANCE.submitSimulation(simulation);
                    digitalClockPanel.start(DigitalClockPanel.Mode.STOPWATCH);
                } catch(Exception ex) {
                    logger.error(ex.getMessage(), ex);
                }
                break;
            case SIMULACION:
                Object[] opciones = {"Seguir con la simulación",
                        "Cancelar simulación"};
                int n = JOptionPane.showOptionDialog(parentFrame,
                    "¿Seguro que desea cancelar la ejecución?",
                    "Confirmar operación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    opciones,
                    opciones[1]);
                logger.debug("JOptionPane - n: " + n); 
                if (n == 0) {//Seguir con la simulación
                    logger.debug("Seguir con la simulación");
                } else if (n == 1) {//Cancelar simulación
                    logger.debug("Cancelar simulación");
                }
                estado = Estado.RECOGIDA_DATOS;
                datosSimulacionButton.setEnabled(true);
                lanzarSimulacionButton.setIcon(null);
                lanzarSimulacionButton.setText("Lanzar simulación");
                lanzarSimulacionButton.setIcon(new ImageIcon(getClass().getResource("/images/gnome-run.png")));
                try {
                    if(votacion != null) executorPool.shutdown();
                } catch(Exception ex) {
                    logger.error(ex.getMessage(), ex);
                }
                digitalClockPanel.stop();
                break;
        }
        contadorPanel.setVisible(true);
        if(mainFrame != null)mainFrame.pack();
    }//GEN-LAST:event_lanzarSimulacionButtonActionPerformed

    private void erroresSolicitudesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erroresSolicitudesButtonActionPerformed
        InfoErroresDialog infoErroresDialog = new InfoErroresDialog(
                parentFrame, false, 
                "Errores en las solicitudes de acceso", accessRequesterrorList);
        infoErroresDialog.setVisible(true);
    }//GEN-LAST:event_erroresSolicitudesButtonActionPerformed

    private void erroresVotosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erroresVotosButtonActionPerformed
        InfoErroresDialog infoErroresDialog = new InfoErroresDialog(
                parentFrame, false, 
                "Errores en los votos", votingerrorList);
        infoErroresDialog.setVisible(true);
    }//GEN-LAST:event_erroresVotosButtonActionPerformed

    private void anularVotosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anularVotosButtonActionPerformed
        AnularVotosDialog anularVotosDialog = new AnularVotosDialog(
                parentFrame, false, evento);
        anularVotosDialog.setVisible(true);
    }//GEN-LAST:event_anularVotosButtonActionPerformed

    private void createUserBaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBaseButtonActionPerformed
        UserBaseDialog userBaseDialog = new UserBaseDialog(parentFrame, false);
        userBaseDialog.setData(ContextoPruebas.INSTANCE.getUserBaseData());
        userBaseDialog.setVisible(true);
    }//GEN-LAST:event_createUserBaseButtonActionPerformed

    public void setControlAcceso(ActorConIP controlAcceso) {
        if(controlAcceso.getCentrosDeControl() != null  &&
                controlAcceso.getCentrosDeControl().size() >0) {
            hashMapActores = new HashMap<String, ActorConIP>();
            ArrayList centrosControlList = new ArrayList();
            Set<ActorConIP> centrosControl = controlAcceso.getCentrosDeControl();
            for(ActorConIP centroControl : centrosControl) {
                centrosControlList.add(centroControl.getServerURL());
                hashMapActores.put(centroControl.getServerURL(), centroControl);
            }
            ArrayListComboBoxModel comboBoxModel = new ArrayListComboBoxModel(centrosControlList);
            centrosDeControlComboBox.setModel(comboBoxModel);
            centrosDeControlComboBox.setSelectedIndex(0);
            ActorConIP centroControlSelected = hashMapActores.get((String)
                    centrosDeControlComboBox.getSelectedItem());
            ContextoPruebas.INSTANCE.setControlCenter(centroControlSelected);
            urlCentroControlPanel.setVisible(true);
            publicacionConvocatoriaPanel.setVisible(true);
        }
    }
    
    public void cargarEvento(Evento evento) {
        this.evento = evento;
        asociarCentroControlButton.setVisible(false);
        centrosDeControlComboBox.setEnabled(false);
        publicacionConvocatoriaPanel.setVisible(false);
        asuntoConvocatoriaLabel.setText("<html><b>Asunto de la convocatoria: </b>"
                + evento.getAsunto() + "</html>");
        asuntoConvocatoriaLabel.setVisible(true);
        datosSimulacionPanel.setVisible(true);
        if(mainFrame != null)mainFrame.pack();
    }
    
    public void enableSimulation(boolean enabled) {
        lanzarSimulacionButton.setVisible(enabled);
    }

    @Override
    public void hyperlinkUpdate(HyperlinkEvent evt) {
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            logger.debug("Pulsado enlace: " + evt.getURL()); 
            if( !java.awt.Desktop.isDesktopSupported() ) {
                logger.debug("La aplicación no tiene acceso al entorno de escritorio");
                return;
            }
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            try {
                desktop.browse(evt.getURL().toURI());
            } catch (Exception ex) {
                logger.error(ex.getMessage(), ex);
            }
        }
    }
    
    
    public class ArrayListComboBoxModel extends AbstractListModel implements ComboBoxModel {
        
        private String selectedItem;
        private ArrayList<String> centrosControl;

        public ArrayListComboBoxModel(ArrayList<String> centrosControl) {
            this.centrosControl = centrosControl;
        }

        public Object getSelectedItem() {
            return selectedItem;
        }

        public void setSelectedItem(Object newValue) {
            selectedItem = (String)newValue;
        }

        public int getSize() {
            return centrosControl.size();
        }

        public Object getElementAt(int i) {
            return centrosControl.get(i);
        }
    }
    
    public void actualizarContadorSolicitudesError(final int numSolicitud) {
        if(SwingUtilities.isEventDispatchThread()) {
            contadorSolicitudesErrorLabel.setText(
                    "<html><b>Solicitudes con error: </b>"
                     + numSolicitud + "</html>");
        } else {
            try {
                SwingUtilities.invokeAndWait(new Runnable() {
                    @Override
                    public void run() {
                        contadorSolicitudesErrorLabel.setText(
                        "<html><b>Solicitudes con error: </b>"
                        + numSolicitud + "</html>");
                    }
                });
            } catch (Exception ex) {
                logger.error(ex.getMessage(), ex);
            }
        }
    }
    
    public void actualizarContadorVotosLanzados(final int numVoto) {
        if(SwingUtilities.isEventDispatchThread()) {
            contadorVotosLabel.setText("<html><b>Lanzado voto: </b>"
                     + numVoto + "</html>");
        } else {
            try {
                SwingUtilities.invokeAndWait(new Runnable() {
                    @Override
                    public void run() {
                        contadorVotosLabel.setText("<html><b>Lanzado voto: </b>"
                     + numVoto + "</html>");
                    }
                });
            } catch (Exception ex) {
                logger.error(ex.getMessage(), ex);
            }
        }
    }
    
    public void actualizarContadorVotosValidados(final int numVoto) {
        if(SwingUtilities.isEventDispatchThread()) {
            contadorVotosValidadosLabel.setText("<html><b>Recolectado voto: </b>"
                     + numVoto + "</html>");
        } else {
            try {
                SwingUtilities.invokeAndWait(new Runnable() {
                    @Override
                    public void run() {
                        contadorVotosValidadosLabel.setText("<html><b>Recolectado voto: </b>"
                        + numVoto + "</html>");
                    }
                });
            } catch (Exception ex) {
                logger.error(ex.getMessage(), ex);
            }
        }
    }
    
    public void actualizarContadorVotosError(final int numVoto) {
        if(SwingUtilities.isEventDispatchThread()) {
            contadorVotosErrorLabel.setText("<html><b>Votos con error: </b>"
                     + numVoto + "</html>");
        } else {
            try {
                SwingUtilities.invokeAndWait(new Runnable() {
                    @Override
                    public void run() {
                        contadorVotosErrorLabel.setText("<html><b>Votos con error: </b>"
                        + numVoto + "</html>");
                    }
                });
            } catch (Exception ex) {
                logger.error(ex.getMessage(), ex);
            }
        }
    }
    
    private void addAccessRequestError(String error) {
        if(accessRequesterrorList == null)
            accessRequesterrorList = new ArrayList<String>();
        accessRequesterrorList.add(error);
    }
    
    private void addVotingError(String error) {
        if(votingerrorList == null)
            votingerrorList = new ArrayList<String>();
        votingerrorList.add(error);
    }
    
    @Override public void processResponse(
            Respuesta<VotingSimulationData> respuesta) {
        switch(respuesta.getCodigoEstado()) {
            case Respuesta.SC_FINALIZADO:
                setSimulationResult(respuesta.getData());
                break;
            default:
                updateSimulationData((VotingSimulationData) respuesta.getData());
                break;
        }
    }
    
    private void updateSimulationData(VotingSimulationData data) {
        if(Respuesta.SC_OK == data.getStatusCode()) {
        
        } else {
            switch(data.getError()) {
                case ACCESS_REQUES:
                    addAccessRequestError(data.getMessage());
                    break;
                case VOTING:
                    addVotingError(data.getMessage());
            }
        }
        actualizarContadorSolicitudesError(
                data.getNumAccessRequestsERROR().intValue());
        actualizarContadorVotosError(
                data.getNumVotingRequestsERROR().intValue());
        actualizarContadorVotosLanzados(
                data.getNumVotingRequests().intValue());
        actualizarContadorVotosValidados(
                data.getNumVotingRequestsColected().intValue());
    }


    private void setSimulationResult(VotingSimulationData simuData) {
        logger.debug("setSimulationResult");

        digitalClockPanel.stop();
        datosSimulacionButton.setEnabled(true);
        lanzarSimulacionButton.setIcon(null);
        lanzarSimulacionButton.setText("Lanzar simulación");
        anularVotosButton.setVisible(true);
        estado = Estado.RECOGIDA_DATOS;

        if(accessRequesterrorList != null && 
                !accessRequesterrorList.isEmpty()) {
            erroresSolicitudesButton.setVisible(true);
        }
        if(votingerrorList != null && !votingerrorList.isEmpty()) {
            erroresVotosButton.setVisible(true);
        }
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                if(mainFrame != null)mainFrame.pack();
            }
        });

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anularVotosButton;
    private javax.swing.JButton asociarCentroControlButton;
    private javax.swing.JLabel asuntoConvocatoriaLabel;
    private javax.swing.JLabel centroControlLabel;
    private javax.swing.JPanel centroControlPanel;
    private javax.swing.JComboBox centrosDeControlComboBox;
    private javax.swing.JPanel contadorPanel;
    private javax.swing.JLabel contadorSolicitudesErrorLabel;
    private javax.swing.JLabel contadorVotosErrorLabel;
    private javax.swing.JLabel contadorVotosLabel;
    private javax.swing.JLabel contadorVotosValidadosLabel;
    private javax.swing.JButton createUserBaseButton;
    private javax.swing.JButton datosSimulacionButton;
    private javax.swing.JPanel datosSimulacionPanel;
    private org.sistemavotacion.test.panel.DigitalClockPanel digitalClockPanel;
    private javax.swing.JButton erroresSolicitudesButton;
    private javax.swing.JButton erroresVotosButton;
    private javax.swing.JButton infoEventoButton;
    private javax.swing.JButton infoServidorButton;
    private javax.swing.JButton lanzarSimulacionButton;
    private javax.swing.JLabel mensajePublicacionLabel;
    private javax.swing.JPanel publicacionConvocatoriaPanel;
    private javax.swing.JButton publicarButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel timePanel;
    private javax.swing.JPanel urlCentroControlPanel;
    // End of variables declaration//GEN-END:variables
}
