package org.centrocontrol.clientegwt.client;

public enum HistoryToken {
	
	VOTACIONES, CREAR_VOTACION, VOTAR, DOCUMENTACION, BUSQUEDAS, 
	OBTENIDA_INFO_SERVIDOR, HERRAMIENTA_VALIDACION, DUMMY_TOKEN, TEST;

}
