package org.votingsystem.crypto;

/**
 * License: https://github.com/votingsystem/votingsystem/wiki/Licencia
 */
public enum SignedDocumentType {

    //currency operations
    CLOSE_SESSION,
    BANK_NEW,
    SESSION_CERTIFICATION,
    SESSION_CERTIFICATION_RECEIPT,
    DEVICE_REGISTER,
    DEVICE_SESSION,

    TRANSACTION_FROM_BANK,
    TRANSACTION_FROM_BANK_RECEIPT,

    TRANSACTION_FROM_USER,
    TRANSACTION_FROM_USER_RECEIPT,

    CURRENCY_REQUEST,
    CURRENCY_CHANGE,
    CURRENCY_CHANGE_RECEIPT,
    CURRENCY_SEND,
    CURRENCY_SEND_RECEIPT,
    CURRENCY_PERIOD_INIT,

    //Admin documents
    ADMIN_CHECK_USER,
    ADMIN_BATCH_RECEIPT,

    SIGNED_DOCUMENT,

    ENTITY_METADATA,
    NEW_ELECTION_REQUEST,
    ANON_VOTE_CERT_REQUEST_REPEATED,
    ANON_VOTE_CERT_REQUEST,
    VOTE_REPEATED,
    VOTE;
}
