package org.votingsystem.util;

/**
 * Locale.getISOCountries()
 *
 * License: https://github.com/votingsystem/votingsystem/wiki/Licencia
 */
public enum Country {

    AD("Andorra"),
    AE("Emiratos Árabes Unidos"),
    AF("Afganistán"),
    AG("Antigua y Barbuda"),
    AI("Anguila"),
    AL("Albania"),
    AM("Armenia"),
    AN("Antillas Holandesas"),
    AO("Angola"),
    AQ("Antártida"),
    AR("Argentina"),
    AS("Samoa Americana"),
    AT("Austria"),
    AU("Australia"),
    AW("Aruba"),
    AX("Islas Aland"),
    AZ("Azerbaiyán"),
    BA("Bosnia y Hercegovina"),
    BB("Barbados"),
    BD("Bangladesh"),
    BE("Bélgica"),
    BF("Burkina Faso"),
    BG("Bulgaria"),
    BH("Bahráin"),
    BI("Burundi"),
    BJ("Benín"),
    BL("San Bartolomé"),
    BM("Bermudas"),
    BN("Brunéi"),
    BO("Bolivia"),
    BQ("Bonaire, San Eustaquio y Saba"),
    BR("Brasil"),
    BS("Bahamas"),
    BT("Bután"),
    BV("Isla Bouvet"),
    BW("Botsuana"),
    BY("Bielorrusia"),
    BZ("Belice"),
    CA("Canadá"),
    CC("Islas Cocos"),
    CD("República Democrática del Congo"),
    CF("República Centroafricana"),
    CG("Congo"),
    CH("Suiza"),
    CI("Costa de Marfil"),
    CK("Islas Cook"),
    CL("Chile"),
    CM("Camerún"),
    CN("China"),
    CO("Colombia"),
    CR("Costa Rica"),
    CU("Cuba"),
    CV("Cabo Verde"),
    CW("Curaçao"),
    CX("Isla Christmas"),
    CY("Chipre"),
    CZ("Chequia"),
    DE("Alemania"),
    DJ("Yibuti"),
    DK("Dinamarca"),
    DM("Dominica"),
    DO("República Dominicana"),
    DZ("Argelia"),
    EC("Ecuador"),
    EE("Estonia"),
    EG("Egipto"),
    EH("Sahara Occidental"),
    ER("Eritrea"),
    ES("España"),
    ET("Etiopía"),
    FI("Finlandia"),
    FJ("Fiyi"),
    FK("Islas Malvinas"),
    FM("Micronesia"),
    FO("Islas Feroe"),
    FR("Francia"),
    GA("Gabón"),
    GB("Reino Unido"),
    GD("Granada"),
    GE("Georgia"),
    GF("Guayana Francesa"),
    GG("Guernsey"),
    GH("Ghana"),
    GI("Gibraltar"),
    GL("Groenlandia"),
    GM("Gambia"),
    GN("Guinea"),
    GP("Guadalupe"),
    GQ("Guinea Ecuatorial"),
    GR("Grecia"),
    GS("Islas Georgia del Sur y Sandwich del Sur"),
    GT("Guatemala"),
    GU("Guam"),
    GW("Guinea-Bissau"),
    GY("Guyana"),
    HK("Hong Kong"),
    HM("Islas Heard y McDonald"),
    HN("Honduras"),
    HR("Croacia"),
    HT("Haití"),
    HU("Hungría"),
    ID("Indonesia"),
    IE("Irlanda"),
    IL("Israel"),
    IM("Isla de Man"),
    IN("India"),
    IO("Territorio Británico del Océano Índico"),
    IQ("Iraq"),
    IR("Irán"),
    IS("Islandia"),
    IT("Italia"),
    JE("Jersey"),
    JM("Jamaica"),
    JO("Jordania"),
    JP("Japón"),
    KE("Kenia"),
    KG("Kirguizistán"),
    KH("Camboya"),
    KI("Kiribati"),
    KM("Comores"),
    KN("San Cristóbal y Nieves"),
    KP("Corea del Norte"),
    KR("Corea del Sur"),
    KW("Kuwait"),
    KY("Islas Caimán"),
    KZ("Kazajstán"),
    LA("Laos"),
    LB("Líbano"),
    LC("Santa Lucia"),
    LI("Liechtenstein"),
    LK("Sri Lanka"),
    LR("Liberia"),
    LS("Lesoto"),
    LT("Lituania"),
    LU("Luxemburgo"),
    LV("Letonia"),
    LY("Libia"),
    MA("Marruecos"),
    MC("Mónaco"),
    MD("Moldavia"),
    ME("Montenegro"),
    MF("San Martín"),
    MG("Madagascar"),
    MH("Islas Marshall"),
    MK("Macedonia"),
    ML("Malí"),
    MM("Myanmar"),
    MN("Mongolia"),
    MO("Macao"),
    MP("Islas Marianas del Norte"),
    MQ("Martinica"),
    MR("Mauritania"),
    MS("Montserrat"),
    MT("Malta"),
    MU("Mauricio"),
    MV("Maldivas"),
    MW("Malaui"),
    MX("México"),
    MY("Malasia"),
    MZ("Mozambique"),
    NA("Namibia"),
    NC("Nueva Caledonia"),
    NE("Níger"),
    NF("Isla Norfolk"),
    NG("Nigeria"),
    NI("Nicaragua"),
    NL("Holanda"),
    NO("Noruega"),
    NP("Nepal"),
    NR("Nauru"),
    NU("Niue"),
    NZ("Nueva Zelanda"),
    OM("Omán"),
    PA("Panamá"),
    PE("Perú"),
    PF("Polinesia Francesa"),
    PG("Papúa New Guinea"),
    PH("Filipinas"),
    PK("Paquistán"),
    PL("Polonia"),
    PM("San Pedro y Miquelón"),
    PN("Islas Pitcairn"),
    PR("Puerto Rico"),
    PS("Palestina"),
    PT("Portugal"),
    PW("Palaos"),
    PY("Paraguay"),
    QA("Qatar"),
    RE("Reunión"),
    RO("Rumania"),
    RS("Serbia"),
    RU("Rusia"),
    RW("Ruanda"),
    SA("Arabia Saudita"),
    SB("Islas Salomón"),
    SC("Seychelles"),
    SD("Sudán"),
    SE("Suecia"),
    SG("Singapur"),
    SH("Santa Helena"),
    SI("Eslovenia"),
    SJ("Svalbard y Jan Mayen"),
    SK("Eslovaquia"),
    SL("Sierra Leona"),
    SM("San Marino"),
    SN("Senegal"),
    SO("Somalia"),
    SR("Surinam"),
    SS("Sudán del Sur"),
    ST("Santo Tomé y Príncipe"),
    SV("El Salvador"),
    SX("San Martín (región holandesa)"),
    SY("Siria"),
    SZ("Suazilandia"),
    TC("Islas Turcas y Caicos"),
    TD("Chad"),
    TF("Territorios Franceses del Sur"),
    TG("Togo"),
    TH("Tailandia"),
    TJ("Tayikistán"),
    TK("Tokelau"),
    TL("Timor Oriental"),
    TM("Turkmenistán"),
    TN("Túnez"),
    TO("Tonga"),
    TR("Turquía"),
    TT("Trinidad y Tobago"),
    TV("Tuvalu"),
    TW("Taiwán"),
    TZ("Tanzania"),
    UA("Ucrania"),
    UG("Uganda"),
    UM("Islas menores alejadas de los Estados Unidos"),
    US("Estados Unidos"),
    UY("Uruguay"),
    UZ("Uzbekistán"),
    VA("Ciudad del Vaticano"),
    VC("San Vicente y las Granadinas"),
    VE("Venezuela"),
    VG("Islas Vírgenes Británicas"),
    VI("Islas Vírgenes Americanas"),
    VN("Vietnam"),
    VU("Vanuatu"),
    WF("Wallis y Futuna"),
    WS("Samoa"),
    YE("Yemen"),
    YT("Mayotte"),
    ZA("Sudáfrica"),
    ZM("Zambia"),
    ZW("Zimbabue");

    private String displayCountry;

    Country(String displayCountry) {
        this.displayCountry = displayCountry;
    }

    public String getDisplayCountry() {
        return displayCountry;
    }

}
